name : "cd pipelone"

on:
    workflow_run:
        workflows: ["react CICD pipeline / workflow"]
        types: 
            - completed
    workflow_dispatch:
        
        
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name : "setup nodejs"
              uses: actions/setup-node@v3
              with:
                    node-version: '16'
            - name : " setup vercel"
              run: npm i -g vercel

            - name: "download the artifact"
              uses: actions/download-artifact@v4
              with:
                name: build
               
                run-id: ${{ github.event.workflow_run.id }}
                github-token: ${{ secrets.GITHUB_TOKEN }}
            - name: "lsit the directory"
              run: ls 

            - name: "deploy to vercel"
              run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm --name="react-cicd-pipeline" --scope "react-cicd-pipeline"                
               

            - name: "deploy to production server"
              run: echo "deploying to production server" 